
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "geodemo"
  end
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "geodemo-vagrant"
  config.vm.network "private_network", ip: "192.168.50.5",
    nic_type: "virtio"
end
